### ISSUE TITLE
建议和交流

### ISSUE THREAD

**Issue by shui9527** [xuan06zyx/blive-vod#1]
恰巧我也在写这个配合lx播放器的插件，细看了一下你的代码，发现有几个问题。
1、看到有添加歌曲到songlist，但是没有看到关于songlist的其他相关代码。
2、似乎点歌就直接使用webbrowser打开Scheme URL，多人点歌的时候不太方便。
3、点歌的正则表达式，似乎没有办法应对带歌手名点歌的字符串？
4、http协议轮询的方式简单直接，但是似乎容易出问题（之前有过）
5、lxmusic的类真棒，我抄走了，谢谢

非专业人士，业余爱好者的粗浅认知，说得不对的请不要在意。

建议完善songlist和相关逻辑，以及使用ws协议获取弹幕
ws协议 可以用[blivedm](https://github.com/xfgryujk/blivedm)
如果有闲空的话，希望能加个联系方式，多多交流，希望能参考你的代码帮助我完善一下我写的那个工具。

**Comment by xuan06zyx** [comment]
1.songlist是我之前项目的遗留 原本是打开一个ws服务器让js可以获取到然后放在obs上展示歌单（现在因为lx的播放列表不对外还有我懒就搁置了）
2.我不清楚多人点歌的时候为什么不方便，因为关于打开Scheme URL是问的GPT（doge）
3.忘记了 因为代码是直接复用的前项目
4.确实很容易出问题 前两天因为未知原因这个历史弹幕的接口没有任何值了，我被迫寻找以及测试了一天ws弹幕接口相关的项目（最后因为接口能用了以及异步代码看得我头疼也是搁置了）
5.封装出来就是方便抄的
blivedm那个项目我看过，具体原因在第四条
个人常用的联系方式我写在readme了 或者说需要其他的联系方式？

**Comment by xuan06zyx** [comment]
第三点和第四点已于今日完成更新
https://github.com/xuan06zyx/blive-vod/commit/f94a6c4902bfe7e2b56739bfde64742938cff9aa

**Comment by shui9527** [comment]
厉害，好快。
我这2天都在头痛pyside6做界面，界面逻辑好麻烦。

**Comment by xuan06zyx** [comment]
> 厉害，好快。 我这2天都在头痛pyside6做界面，界面逻辑好麻烦。

所以我根本没做gui（doge）我可能学了qt再考虑gui了 前端我也是不感兴趣

**Comment by shui9527** [comment]
diange = re.match(r'点歌\s+(\S+)(?:\s+(\S+))?', msg)
        if diange:
            song_name = diange.group(1)  # 匹配的歌名
            song_singer = diange.group(2) if diange.group(2) else ""  # 匹配的歌手 如果没有指定则为空
            
遇到 类似这样的弹幕： ‘点歌 青花瓷 可以吗？’
会把“可以吗？”当做歌手吧。我想不出有什么跟更好的办法做这个判断筛选，你有好点子吗

**Comment by xuan06zyx** [comment]
> diange = re.match(r'点歌\s+(\S+)(?:\s+(\S+))?', msg) if diange: song_name = diange.group(1) # 匹配的歌名 song_singer = diange.group(2) if diange.group(2) else "" # 匹配的歌手如果没有指定则为空
> 
> 遇到类似这样的弹幕：‘点歌青花瓷可以吗？’ 会把“可以吗？”当做歌手吧。我想不出有什么跟更好的办法做这个判断筛选，你有好点子吗

要不就把现今所有歌手的名字记录下来然后匹配，但是。。。反正我不会 歌手会由各种不同的文字组成 遇到这种几乎无解的难题我只会在readme加上提示。。。

**Comment by shui9527** [comment]
更新2.8版本的LX 以后，出现SSE连接超时的情况 你有遇到吗

**Comment by shui9527** [comment]
我有一段代码


def run(self):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(self.send_data())

async def get_data(self):
    async with aiohttp.ClientSession() as session:
        try:
            async with session.get("http://localhost:23330/subscribe-player-status") as response:
               while True:
                    line = await response.content.readline()
                    event = str(line.decode('utf-8').strip())
                    yield event
        except aiohttp.ClientConnectorError:
            event = '无法连接播放器 : 请确认已打开LX播放器'
            yield event

async def send_data(self):
    async for event in self.get_data():
        self.data_updated.emit(event)
        
        
运行一会就会出现
        
        
        
Traceback (most recent call last):
File "E:\Users\shuis\python\LiveToolBox\monitevent.py", line 13, in run
loop.run_until_complete(self.process_data())
File "D:\Anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "E:\Users\shuis\python\LiveToolBox\monitevent.py", line 29, in process_data
async for event in self.get_data():
File "E:\Users\shuis\python\LiveToolBox\monitevent.py", line 20, in get_data
line = await response.content.readline()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Anaconda3\Lib\site-packages\aiohttp\streams.py", line 307, in readline
return await self.readuntil()
^^^^^^^^^^^^^^^^^^^^^^
File "D:\Anaconda3\Lib\site-packages\aiohttp\streams.py", line 341, in readuntil
await self._wait("readuntil")
File "D:\Anaconda3\Lib\site-packages\aiohttp\streams.py", line 301, in _wait
with self._timer:
File "D:\Anaconda3\Lib\site-packages\aiohttp\helpers.py", line 735, in exit
raise asyncio.TimeoutError from None
TimeoutError

**Comment by xuan06zyx** [comment]
> 更新2.8版本的LX 以后，出现SSE连接超时的情况 你有遇到吗

不清楚 我没有调用open api

**Comment by Drdongm** [comment]
> diange = re.match(r'点歌\s+(\S+)(?:\s+(\S+))?', msg) if diange: song_name = diange.group(1) # 匹配的歌名 song_singer = diange.group(2) if diange.group(2) else "" # 匹配的歌手 如果没有指定则为空
> 
> 遇到 类似这样的弹幕： ‘点歌 青花瓷 可以吗？’ 会把“可以吗？”当做歌手吧。我想不出有什么跟更好的办法做这个判断筛选，你有好点子吗

当匹配不上歌手的时候要么点歌失败，要么默认搜索到的第一首歌，个人认为是符合逻辑的。请问我是有什么地方没有考虑到吗>_<

**Comment by QDLinux** [comment]
> > diange = re.match(r'点歌\s+(\S+)(?:\s+(\S+))?', msg) if diange: song_name = diange.group(1) # 匹配的歌名 song_singer = diange.group(2) if diange.group(2) else "" # 匹配的歌手 如果没有指定则为空
> > 遇到 类似这样的弹幕： ‘点歌 青花瓷 可以吗？’ 会把“可以吗？”当做歌手吧。我想不出有什么跟更好的办法做这个判断筛选，你有好点子吗
> 
> 当匹配不上歌手的时候要么点歌失败，要么默认搜索到的第一首歌，个人认为是符合逻辑的。请问我是有什么地方没有考虑到吗>_<

emmm，我刚刚pr的版本可能会修复这个问题，因为我把搜索逻辑单独列出来了，你有空可以试一下然后给我反馈（
